### ISSUE TITLE
improve time picker

### ISSUE THREAD

**Issue by Tuinslak** [FlatTurtle/Reservations#51]
als ge "9:00" invult ipv "09:00" werkt da ni

Yeri Tiete [9:17 AM]
en "09h00" ook ni

Yeri Tiete [9:17 AM]
en "9h" enzo ook ni

regex:

Nik Torfs [9:17 AM] 
[0-9]{1,2}:[0-9]{2}

make it a dropdown: hours and per 15 mins

**Comment by niktorfs** [comment]
Foute repo. Dit hoort bij sitecore
